a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
print("addition:",a+b)
print("Subcrtion:",a-b)
print("multiplication:",a*b)
print("division:",a/b)
print("floor division:",a//b)
print("exponention:",a**b)
print("modulus:",a%b)
